baseurl = "https://jug.sh" # Controls base URL
languageCode = "en-US" # Controls html lang attribute
title = "jug shell" # Homepage title and page title suffix
paginate = 5 # Number of posts to show before paginating
theme = "after-dark"

enableRobotsTXT = true # Suggested, enable robots.txt file
googleAnalytics = "" # Optional, add tracking Id for analytics
SectionPagesMenu = "main" # Enable menu system for lazy bloggers

[params]
  description = "things you might want to do" # Suggested, controls homepage description meta
  author = "Sebastian Jug" # Optional, controls author name display on posts
  show_menu = true # Optional, set false to disable menu entirely
  powered_by = false # Optional, set false to disable theme credits

  [params.seo]
    google_verify = "" # Optional, Google verification code
    bing_verify = "" # Optional, Bing verification code
    yandex_verify = "" # Optional, Yandex verification code

[menu]
  [[menu.main]]
    name = "Home"
    weight = 0
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    weight = 1
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "About"
    weight = 2
    identifier = "about"
    url = "/about/"
